on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, reopened, synchronize]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          pytest
  